"""A minimal, valid, clearly-synthetic case package template.

``case-package init`` writes exactly this content to a new file so a
researcher unfamiliar with the schema has something concrete and already
valid to read, edit, and re-validate -- never anything resembling real
forensic evidence. See docs/research/witnessgraph-case-format.md and
docs/research/witnessgraph-quickstart.md.
"""

from __future__ import annotations

from datetime import UTC, datetime

from witnessgraph.casepkg.schema import (
    CASE_PACKAGE_SCHEMA_VERSION,
    CaseMetadata,
    CasePackage,
    DeclaredEntity,
    DeclaredEvidenceItem,
    DeclaredRelationship,
)

DEMO_LABEL = "DEMO / TEMPLATE DATA -- not real forensic evidence"


def build_demo_case_package() -> CasePackage:
    now = datetime(2026, 1, 1, tzinfo=UTC)
    return CasePackage(
        schema_version=CASE_PACKAGE_SCHEMA_VERSION,
        package_version="0.1.0",
        case_metadata=CaseMetadata(
            title=f"{DEMO_LABEL}: demo case",
            description=(
                f"{DEMO_LABEL}. A minimal, synthetic example generated by "
                "`witnessgraph case-package init` to demonstrate the case "
                "package schema. Every identifier below is a made-up "
                "placeholder; edit or replace this entire file before "
                "declaring a real case."
            ),
            created_by="witnessgraph case-package init",
            created_at=now,
        ),
        evidence_items=(
            DeclaredEvidenceItem(
                local_id="demo-evidence-1",
                content='{"demo": true, "note": "synthetic auth log line"}',
                source_locator="demo/auth.log:1",
                collected_at=now,
                source_id=None,
            ),
        ),
        entities=(
            DeclaredEntity(
                local_id="demo-host",
                entity_type="host",
                identifiers={"hostname": "demo-host-01"},
                derived_from=("demo-evidence-1",),
            ),
            DeclaredEntity(
                local_id="demo-user",
                entity_type="user",
                identifiers={"username": "demo-user-01"},
                derived_from=("demo-evidence-1",),
            ),
        ),
        relationships=(
            DeclaredRelationship(
                local_id=None,
                relationship_type="authenticated_as",
                source_entity="demo-user",
                target_entity="demo-host",
                derived_from=("demo-evidence-1",),
                created_at=now,
            ),
        ),
    )
