"""Store / BlobStore protocols that the rest of Witnessgraph depends on.

See DESIGN.md principle 6: any implementation of these protocols must be
local-first and must never open a network listener or make an outbound
network call.
"""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from witnessgraph.core.entities import Entity
from witnessgraph.core.events import NormalizedEvent
from witnessgraph.core.evidence import EvidenceItem
from witnessgraph.core.hypothesis import Hypothesis
from witnessgraph.core.time_model import TimeAssertion
from witnessgraph.core.tracked_finding import FindingStatus, TrackedGapFinding


class Store(Protocol):
    """Metadata storage for one case's evidence graph."""

    def put_evidence(self, item: EvidenceItem) -> None: ...
    def get_evidence(self, id: str) -> EvidenceItem | None: ...
    def list_evidence(self) -> list[EvidenceItem]: ...

    def put_normalized_event(self, event: NormalizedEvent) -> None: ...
    def get_normalized_event(self, id: str) -> NormalizedEvent | None: ...
    def list_normalized_events(self) -> list[NormalizedEvent]: ...

    def put_entity(self, entity: Entity) -> None: ...
    def get_entity(self, id: str) -> Entity | None: ...
    def list_entities(self) -> list[Entity]: ...

    def put_time_assertion(self, assertion: TimeAssertion) -> None: ...
    def list_time_assertions(self) -> list[TimeAssertion]: ...

    def put_hypothesis(self, hypothesis: Hypothesis) -> None: ...
    def get_hypothesis(self, id: str) -> Hypothesis | None: ...
    def list_hypotheses(self) -> list[Hypothesis]: ...

    def create_tracked_finding(self, finding: TrackedGapFinding) -> TrackedGapFinding: ...
    def annotate_tracked_finding(
        self,
        id: str,
        *,
        status: FindingStatus,
        annotated_by: str,
        annotated_at: datetime,
        note: str | None,
    ) -> TrackedGapFinding: ...
    def get_tracked_finding(self, id: str) -> TrackedGapFinding | None: ...
    def list_tracked_findings(self) -> list[TrackedGapFinding]: ...

    def close(self) -> None: ...


class BlobStore(Protocol):
    """Content-addressed storage for raw evidence bytes.

    See DESIGN.md principle 1: once written, a blob is never modified;
    the same bytes always produce the same address, and writing the same
    bytes twice is a no-op.
    """

    def put(self, data: bytes) -> str: ...
    def get(self, content_hash: str) -> bytes: ...
    def has(self, content_hash: str) -> bool: ...
